export const computerActivities = [
    "Checking Email",
    "Writing Documents",
    "Creating Spreadsheets",
    "Making Presentations",
    "Browsing the Internet",
    "Watching Videos",
    "Listening to Music",
    "Playing Games",
    "Programming",
    "Coding Websites",
    "Online Shopping",
    "Banking Online",
    "Paying Bills",
    "Social Media Browsing",
    "Video Calling",
    "Messaging",
    "Downloading Files",
    "Uploading Files",
    "Editing Photos",
    "Editing Videos",
    "Streaming Movies",
    "Reading News",
    "Writing Blogs",
    "Managing Calendar",
    "Scheduling Meetings",
    "Taking Notes",
    "Organizing Files",
    "Backing Up Data",
    "Installing Software",
    "Updating Applications",
    "Using Cloud Storage",
    "Designing Graphics",
    "Drawing or Illustrating",
    "Listening to Podcasts",
    "Researching Topics",
    "Creating Databases",
    "Managing Projects",
    "Attending Webinars",
    "Learning Online Courses",
    "Checking Weather",
    "Booking Travel",
    "Making Reservations",
    "Printing Documents",
    "Scanning Documents",
    "Participating in Forums",
    "Moderating Communities",
    "Writing Emails",
    "Tracking Expenses",
    "Budgeting",
    "Writing Code Reviews",
    "Collaborating Remotely",
    "Managing Passwords",
    "Customizing Desktop",
    "Changing Wallpapers",
    "Adjusting Settings",
    "Troubleshooting Issues",
    "Watching Tutorials",
    "Reading eBooks",
    "Typing",
    "Proofreading",
    "Job Searching",
    "Uploading Photos",
    "Commenting Online",
    "Listening to Online Radio",
    "Creating Playlists",
    "Burning CDs/DVDs",
    "Encrypting Files",
    "Compressing Files",
    "Decompressing Files",
    "Monitoring System Performance",
    "Managing Emails",
    "Checking Notifications",
    "Recording Audio",
    "Streaming Live Content",
    "Reading Blogs",
    "Writing Reviews",
    "Creating Animations",
    "Testing Software",
    "Using Virtual Machines",
    "Mapping Routes",
    "Reviewing Analytics",
    "Filing Taxes",
    "Completing Forms",
    "Watching Live Streams",
    "Managing Contacts",
    "Synchronizing Devices",
    "Playing Online Multiplayer Games",
    "Taking Screenshots",
    "Transferring Data",
    "Checking Sports Scores",
    "Tracking Deliveries",
    "Reading Documentation",
    "Answering Surveys",
    "Creating Backups",
    "Browsing Portfolios",
    "Learning Languages",
    "Conducting Interviews"
  ];
  