export const everydayObjects = [
    "Toothbrush",
    "Toothpaste",
    "Soap",
    "Shampoo",
    "Hairbrush",
    "Comb",
    "Mirror",
    "Towel",
    "Coffee Mug",
    "Tea Cup",
    "Water Bottle",
    "Fork",
    "Spoon",
    "Knife",
    "Plate",
    "Bowl",
    "Glass",
    "Napkin",
    "Chair",
    "Table",
    "Bed",
    "Pillow",
    "Blanket",
    "Alarm Clock",
    "Smartphone",
    "Laptop",
    "Tablet",
    "Charger",
    "Headphones",
    "Backpack",
    "Wallet",
    "Keys",
    "Pen",
    "Pencil",
    "Notebook",
    "Book",
    "Calendar",
    "Watch",
    "Glasses",
    "Sunglasses",
    "Shoes",
    "Socks",
    "Shirt",
    "Pants",
    "Jacket",
    "Hat",
    "Umbrella",
    "Bag",
    "Scissors",
    "Tape",
    "Glue",
    "Stapler",
    "Paperclip",
    "Envelope",
    "Flashlight",
    "Remote Control",
    "Television",
    "Refrigerator",
    "Microwave",
    "Stove",
    "Oven",
    "Dishwasher",
    "Washer",
    "Dryer",
    "Vacuum Cleaner",
    "Broom",
    "Dustpan",
    "Trash Bin",
    "Recycling Bin",
    "Door Handle",
    "Light Switch",
    "Lamp",
    "Window",
    "Curtains",
    "Fan",
    "Air Conditioner",
    "Heater",
    "Thermostat",
    "Camera",
    "Printer",
    "Mouse",
    "Keyboard",
    "Desk",
    "Drawer",
    "Shelf",
    "Closet",
    "Toilet",
    "Sink",
    "Shower",
    "Bathtub",
    "Iron",
    "Ironing Board",
    "Detergent",
    "Cleaning Spray",
    "Tissue Box",
    "Medicine Bottle",
    "First Aid Kit",
    "Bandage",
    "Cooking Pan",
    "Pot",
    "Cutting Board"
  ];
  