export const humanStruggles = [
    "Loneliness",
    "Isolation",
    "Fear of Failure",
    "Fear of Rejection",
    "Fear of Abandonment",
    "Fear of Death",
    "Fear of the Unknown",
    "Social Anxiety",
    "Generalized Anxiety",
    "Panic Attacks",
    "Imposter Syndrome",
    "Self-Doubt",
    "Low Self-Esteem",
    "Depression",
    "Major Depression",
    "Seasonal Depression",
    "Grief",
    "Heartbreak",
    "Insecurity",
    "Anhedonia",
    "Insomnia",
    "Nightmares",
    "Existential Crisis",
    "Burnout",
    "Chronic Fatigue",
    "Stress Overload",
    "Financial Anxiety",
    "Career Uncertainty",
    "Relationship Struggles",
    "Divorce",
    "Loss of Loved Ones",
    "Trauma",
    "Post-Traumatic Stress",
    "Addiction",
    "Substance Abuse",
    "Eating Disorders",
    "Body Dysmorphia",
    "Perfectionism",
    "Procrastination",
    "Self-Sabotage",
    "Fear of Commitment",
    "Fear of Intimacy",
    "Codependency",
    "Helplessness",
    "Hopelessness",
    "Guilt",
    "Shame",
    "Regret",
    "Anger Issues",
    "Mood Swings",
    "Bipolar Disorder",
    "Obsessive Thoughts",
    "Compulsive Behavior",
    "Paranoia",
    "Phobias",
    "Fear of Heights",
    "Fear of Public Speaking",
    "Fear of Spiders",
    "Fear of Enclosed Spaces",
    "Fear of Flying",
    "Fear of Drowning",
    "Fear of Losing Control",
    "Fear of Pain",
    "Fear of Illness",
    "Health Anxiety",
    "Fear of Aging",
    "Fear of Change",
    "Fear of Responsibility",
    "Identity Crisis",
    "Feeling Misunderstood",
    "Repressed Emotions",
    "Lack of Purpose",
    "Aimlessness",
    "Disillusionment",
    "Cynicism",
    "Alienation",
    "Fear of Conflict",
    "Avoidance",
    "Fear of Judgment",
    "Social Isolation",
    "Homesickness",
    "Cultural Alienation",
    "Feeling Overwhelmed",
    "Decision Paralysis",
    "Chronic Pain",
    "Illness",
    "Disability",
    "Immobility",
    "Economic Hardship",
    "Poverty",
    "Job Loss",
    "Housing Instability",
    "Family Conflict",
    "Parental Pressure",
    "Academic Stress",
    "Work-Life Imbalance",
    "Overthinking",
    "Negative Self-Talk",
    "Loss of Motivation",
    "Emotional Numbness",
    "Despair",
    "Suicidal Thoughts",
    "Loss of Faith"
  ];
  