export const landscapes = [
    "Peak",
    "Summit",
    "Ridge",
    "Mountaintop",
    "Pass",
    "Crest",
    "Saddle",
    "Divide",
    "Spur",
    "Pinnacle",
    "Range",
    "Butte",
    "Outcrop",
    "Valley",
    "Canyon",
    "Basin",
    "Shoulder",
    "Gulch",
    "Gorge",
    "Ravine",
    "Couloir",
    "Hollow",
    "Meadow",
    "Draw",
    "Glacial Valley",
    "River",
    "Stream",
    "Creek",
    "Brook",
    "Cascade",
    "Waterfall",
    "Cataract",
    "Wash",
,   "Rapid",
    "Lake",
    "Alpine Lake",
    "Tarn",
    "Pond",
    "Headwaters",
    "Tributary",
    "Hot Spring",
    "Geyser",
    "Wetland",
    "Marsh",
    "Snowfield",
    "Treeline",
    "Alpine Tundra",
    "Timberline",
    "Forest",
    "Pine Forest",
    "Spruce Forest",
    "Aspen Grove",
    "Lodgepole Stand",
    "Subalpine Zone",
    "Woodland",
    "Thicket",
    "Clearing",
    "Wildflower Field",
    "Boulder Field",
    "Moraine",
    "Scree Field",
    "Talus Slope",
    "Rockslide",
    "Escarpment",
    "Crag",
    "Cliff",
    "Ledge",
    "Chute",
    "Fault",
    "Glacial Erratic",
    "Arête",
    "Horn",
    "Dome",
    "Glacier",
    "Snowpack",
    "Icefield",
    "Snowdrift",
    "Cornice",
    "Icefall",
    "Serac",
    "Crevasse",
    "Trailhead",
    "Switchback",
    "Backcountry",
    "Wilderness Area",
    "Alpine Hut",
    "Saddle Trail",
    "Forest Road",
    "Wildlife Corridor",
    "Game Trail",
    "Elk Meadow",
    "Bear Den",
    "Beaver Pond",
    "Alpine Glow",
    "Chinook Wind",
    "Snowline",
    "Avalanche Chute",
    "Mountain Shadow",
  ];
  