export const literaryForms = [
    "Sonnet",
    "Haiku",
    "Limerick",
    "Villanelle",
    "Ballad",
    "Ode",
    "Elegy",
    "Epic Poem",
    "Lyric Poem",
    "Free Verse",
    "Blank Verse",
    "Couplet",
    "Quatrain",
    "Sestina",
    "Acrostic Poem",
    "Tanka",
    "Ghazal",
    "Pantoum",
    "Cinquain",
    "Rondeau",
    "Roundel",
    "Terza Rima",
    "Found Poem",
    "Concrete Poem",
    "Narrative Poem",
    "Prose Poem",
    "Pastoral Poem",
    "Triolet",
    "Diamante",
    "Dirge",
    "Hymn",
    "Nursery Rhyme",
    "Folk Song",
    "Lullaby",
    "Anthem",
    "Chant",
    "Madrigal",
    "Ballade",
    "Sea Shanty",
    "Work Song",
    "Gospel Song",
    "Jazz Standard",
    "Blues Song",
    "Rap Verse",
    "Spoken Word",
    "Soliloquy",
    "Monologue",
    "Dialogue",
    "Epistle",
    "Essay",
    "Short Story",
    "Novel",
    "Novella",
    "Fable",
    "Fairy Tale",
    "Myth",
    "Legend",
    "Saga",
    "Parable",
    "Allegory",
    "Aphorism",
    "Epigram",
    "Proverb",
    "Manifesto",
    "Memoir",
    "Autobiography",
    "Biography",
    "Journal Entry",
    "Diary",
    "Travelogue",
    "Letter",
    "Speech",
    "Eulogy",
    "Invocation",
    "Prayer",
    "Psalm",
    "Scripture",
    "Verse Drama",
    "Opera Libretto",
    "Satire",
    "Parody",
    "Farce",
    "Tragedy",
    "Comedy",
    "Melodrama",
    "Tall Tale",
    "Mythology",
    "Mystery"
  ];
  