export const mammals = [
    "Black Bear",
    "Grizzly Bear",
    "Mountain Lion",
    "Lynx",
    "Bobcat",
    "Coyote",
    "Gray Wolf",
    "Red Fox",
    "Swift Fox",
    "Kit Fox",
    "Arctic Fox",
    "Marten",
    "Fisher",
    "Wolverine",
    "Striped Skunk",
    "Spotted Skunk",
    "Long-tailed Weasel",
    "Short-tailed Weasel",
    "River Otter",
    "Mink",
    "Raccoon",
    "Ringtail",
    "Badger",
    "Flying Squirrel",
    "Red Squirrel",
    "Fox Squirrel",
    "Abert's Squirrel",
    "Douglas Squirrel",
    "Least Chipmunk",
    "Yellow-pine Chipmunk",
    "Golden-mantled Ground Squirrel",
    "Marmot",
    "Hoary Marmot",
    "Woodchuck",
    "Black-tailed Prairie Dog",
    "White-tailed Prairie Dog",
    "Gunnison's Prairie Dog",
    "Pocket Gopher",
    "Mountain Beaver",
    "Beaver",
    "Muskrat",
    "Bushy-tailed Woodrat",
    "Deer Mouse",
    "Harvest Mouse",
    "Meadow Vole",
    "Red-backed Vole",
    "Long-tailed Vole",
    "Montane Vole",
    "Heather Vole",
    "Water Vole",
    "Grasshopper Mouse",
    "Western Jumping Mouse",
    "Meadow Jumping Mouse",
    "Porcupine",
    "Snowshoe Hare",
    "White-tailed Jackrabbit",
    "Black-tailed Jackrabbit",
    "Desert Cottontail",
    "Mountain Cottontail",
    "Pygmy Rabbit",
    "Pika",
    "Elk",
    "Moose",
    "Mule Deer",
    "White-tailed Deer",
    "Pronghorn",
    "Bison",
    "Bighorn Sheep",
    "Mountain Goat",
    "Shrew",
    "Dusky Shrew",
    "Masked Shrew",
    "Pygmy Shrew",
    "Water Shrew",
    "Little Brown Bat",
    "Big Brown Bat",
    "Silver-haired Bat",
    "Hoary Bat",
    "Townsend's Big-eared Bat",
    "Pallid Bat",
    "Long-eared Myotis",
    "Fringed Myotis",
    "Long-legged Myotis",
    "Yuma Myotis",
    "Small-footed Myotis",
    "Canyon Bat",
    "Brazilian Free-tailed Bat",
    "Eastern Red Bat",
    "Western Red Bat",
    "Northern Myotis",
    "Tri-colored Bat",
    "Pocket Mouse",
    "Ord's Kangaroo Rat",
    "Silky Pocket Mouse",
    "Rock Mouse",
    "Canyon Mouse",
    "Desert Woodrat",
    "Mexican Woodrat",
    "Eastern Cottontail",
    "Northern Grasshopper Mouse"
  ];
  