export const Plants = [
  "Ponderosa Pine",
  "Quaking Aspen",
  "Rocky Mountain Juniper",
  "Mountain Maple",
  "Wax Currant",
  "Boulder Raspberry",
  "Creeping Oregon-Grape",
  "Chokecherry",
  "Shrubby Cinquefoil",
  "Mountain Cactus",
  "Parry's Bellflower",
  "Prairie Pasqueflower",
  "Musk Thistle",
  "Penland's Alpine Fen Mustard",
  "Blowout Beardtongue",
  "Uinta Basin Hookless Cactus",
  "Mountain Sorrel",
  "Capitate Sedge",
  "Mat Muhly",
  "Newberry Knotweed",
  "Red Huckleberry",
  "Witch's Hair Lichen",
  "Cup Lichen",
  "Pacific Silver Fir",
  "Grand Fir",
  "White Spruce",
  "Balsam Poplar",
  "Black Spruce",
  "Little Bluestem",
  "Needlegrass",
  "Wheatgrass",
  "Sand-Reed",
  "Grama Grass",
  "Dropseed",
  "Cottonwood",
  "Big Sagebrush",
  "Gambel Oak",
  "Emory Oak",
  "Silverleaf Oak",
  "Netleaf Oak",
  "Sumac",
  "Buckbrush",
  "Mountain-Mahogany",
  "Bluebunch Wheatgrass",
  "Bluegrass",
  "Junegrass",
  "Galleta Grass",
  "Buffalo Grass",
  "Ringgrass",
  "Needle-and-Thread Grass",
  "Kobresia",
  "Spike Trisetum",
  "Spreading Wheatgrass",
  "Tufted Hairgrass",
  "Mertensia",
  "Sky Pilot",
  "Alpine Sunflower",
  "Alpine Dwarf Columbine",
  "Alpine Forget-Me-Not",
  "Kinnikinnick",
  "Creeping Juniper",
  "Utah Juniper",
  "Western Redcedar",
  "Alpine Larch",
  "Grand Fir",
  "Mountain Hemlock",
  "Western Hemlock",
  "Western Larch",
  "Western White Pine",
  "White Spruce",
  "Whitebark Pine",
  "Pacific Yew",
  "Common Juniper",
  "Creeping Juniper",
  "Rocky Mountain Juniper",
  "Utah Juniper",
  "Western Redcedar",
  "Alpine Larch",
  "Douglas Fir",
  "Engelmann Spruce",
  "Grand Fir",
  "Limber Pine",
  "Lodgepole Pine",
  "Mountain Hemlock",
  "Ponderosa Pine",
  "Subalpine Fir",
  "Western Hemlock",
  "Western Larch",
  "Western White Pine",
  "White Spruce",
  "Whitebark Pine",
  "Pacific Yew",
  "Common Juniper",
  "Creeping Juniper",
  "Rocky Mountain Juniper",
  "Utah Juniper",
  "Western Redcedar",
  "Aspen",
  "Lodgepole Pine",
  "Engelmann Spruce",
  "Subalpine Fir",
  "Douglas Fir",
  "Ponderosa Pine",
  "Blue Spruce",
  "Bristlecone Pine",
  "Whitebark Pine",
  "Limber Pine",
  "Juniper",
  "Mountain Hemlock",
  "Alpine Larch",
  "Cottonwood",
  "Willow",
  "Mountain Alder",
  "Rocky Mountain Maple",
  "Mountain Ash",
  "Western Red Cedar",
  "Western Hemlock",
  "Sagebrush",
  "Rabbitbrush",
  "Mountain Mahogany",
  "Serviceberry",
  "Chokecherry",
  "Bearberry",
  "Snowberry",
  "Buffaloberry",
  "Twinberry",
  "Huckleberry",
  "Thimbleberry",
  "Raspberry",
  "Wild Strawberry",
  "Kinnikinnick",
  "Wild Rose",
  "Fireweed",
  "Indian Paintbrush",
  "Columbine",
  "Bluebell",
  "Lupine",
  "Goldenrod",
  "Arrowleaf Balsamroot",
  "Glacier Lily",
  "Pasqueflower",
  "Yarrow",
  "Monkshood",
  "Gentian",
  "Shooting Star",
  "Elephanthead",
  "Penstemon",
  "Larkspur",
  "Blue Flax",
  "Wild Geranium",
  "Prairie Smoke",
  "Stonecrop",
  "Bitterroot",
  "Forget-me-not",
  "Wild Onion",
  "Mountain Sorrel",
  "Beargrass",
  "Meadow Rue",
  "Cinquefoil",
  "Yellow Monkeyflower",
  "Scarlet Gilia",
  "Phlox",
  "Mountain Harebell",
  "Buttercup",
  "Mariposa Lily",
  "Woodland Star",
  "Sego Lily",
  "Valerian",
  "Sticky Geranium",
  "Cow Parsnip",
  "Western Anemone",
  "Heartleaf Arnica",
  "Blue Camas",
  "Wild Iris",
  "Wild Mint",
  "Horsemint",
  "Wild Parsley",
  "Snow Buttercup",
  "Bearberry Honeysuckle",
  "White Marsh Marigold",
  "Showy Daisy",
  "Oxeye Daisy",
  "Sulfur Flower",
  "Wild Bergamot",
  "Mountain Bluebells",
  "Wild Licorice",
  "Wild Sage",
  "Foothills Arnica",
  "Alpine Forget-me-not",
  "Silky Lupine",
  "Western Meadowrue",
  "Mountain Gentian",
  "Sneezeweed",
  "Pink Mountain Heather",
  "White Mountain Heather"
];
