export const weatherpatterns = [
    "Snowstorm",
    "Thunderstorm",
    "Blizzard",
    "Flurries",
    "Chinook Winds",
    "Avalanche Conditions",
    "Hailstorm",
    "Sleet",
    "Heavy Rain",
    "Drizzle",
    "Freezing Rain",
    "Fog",
    "Dense Fog",
    "Mist",
    "Cloud Cover",
    "Overcast Skies",
    "Clear Skies",
    "Sunny",
    "Partly Cloudy",
    "Mostly Cloudy",
    "Cold Front",
    "Warm Front",
    "High Pressure",
    "Low Pressure",
    "Gusty Winds",
    "Windstorm",
    "High Winds",
    "Calm Winds",
    "Alpenglow",
    "Mountain Wave Clouds",
    "Lenticular Clouds",
    "Cirrus Clouds",
    "Cumulus Clouds",
    "Cumulonimbus Clouds",
    "Stratus Clouds",
    "Snow Squall",
    "Graupel",
    "Ice Storm",
    "Rime Ice",
    "Frost",
    "Hard Freeze",
    "Soft Freeze",
    "Cold Snap",
    "Deep Freeze",
    "Spring Thaw",
    "Heat Wave",
    "Drought Conditions",
    "Wildfire Smoke",
    "Smoke Haze",
    "Dust Storm",
    "Microburst",
    "Downslope Winds",
    "Upslope Winds",
    "Inversion Layer",
    "Temperature Inversion",
    "Lightning Storm",
    "Cloud-to-Ground Lightning",
    "Thunder",
    "Virga",
    "Rainbow",
    "Double Rainbow",
    "Sun Shower",
    "Freezing Fog",
    "Hoarfrost",
    "Sublimation",
    "Snowpack Accumulation",
    "Snowmelt Runoff",
    "Seasonal Flooding",
    "Flash Flood",
    "Monsoon Rain",
    "Dry Lightning",
    "Dust Devil",
    "Thermal Lift",
    "Föhn Wind",
    "Snow Line",
    "Tree Line Weather",
    "Alpine Weather",
    "Subalpine Weather",
    "High Altitude Conditions",
    "Wind Chill",
    "Heat Index",
    "Humidity",
    "Dew Point",
    "Atmospheric Pressure Drop",
    "Barometric Pressure Rise",
    "Jet Stream Influence",
    "Polar Vortex Influence",
    "Cold-Air Outbreak",
    "Arctic Blast",
    "Cloudburst",
    "Mountain Shadow Effect",
    "Precipitation Shadow",
    "Rain Shadow",
    "Orographic Lift",
    "Squall Line",
    "Severe Thunderstorm",
    "Stable Air Mass",
    "Unstable Air Mass",
    "Storm Front Passage"
  ];
  